#!/bin/sh
set -ev

# Prepare source folders
rm -rf /var/www/html
ln -s /app/$DOCUMENT_ROOT /var/www/html

# Create app user
addgroup --gid $HOST_GID terra

echo $HOST_UID
echo $HOST_GID

adduser --uid $HOST_UID --gid $HOST_GID --system --no-create-home --home /var/www/html terra
adduser terra www-data

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
